E_ticaret_MVC_projesi/Controllers/uyelersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_ticaret_MVC_projesi.Models;

namespace E_ticaret_MVC_projesi.Controllers
{
    public class uyelersController : Controller
    {
        private E_ticaretEntities db = new E_ticaretEntities();

        // GET: uyelers
        public async Task<ActionResult> Index()
        {
            if (Session["admin"] != null)
            {
                var uyeler = db.uyeler.Include(u => u.meslek).Include(u => u.sehirler);
                return View(await uyeler.ToListAsync());
            }
            else
                return HttpNotFound();
        }

        // GET: uyelers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            uyeler uyeler = await db.uyeler.FindAsync(id);
            if (uyeler == null)
            {
                return HttpNotFound();
            }
            return View(uyeler);
        }

        // GET: uyelers/Create
        public ActionResult Create()
        {
            ViewBag.meslekid = new SelectList(db.meslek, "meslekid", "meslekad");
            ViewBag.plaka = new SelectList(db.sehirler, "plaka", "sehiradi");
            return View();
        }

        // POST: uyelers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "uyeid,kuladi,sifre,adsoyad,dogtar,cinsiyet,adres,plaka,email,meslekid,onay")] uyeler uyeler)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.uyeler.Add(uyeler);
                    await db.SaveChangesAsync();
                    ViewBag.sonuc = "Kayıt başarılı";
                }
            }
            catch (Exception)
            {
                ViewBag.sonuc = "Aynı mail kuladi var ...Kayıt yapılamıyor!!!";
            }

            ViewBag.meslekid = new SelectList(db.meslek, "meslekid", "meslekad", uyeler.meslekid);
            ViewBag.plaka = new SelectList(db.sehirler, "plaka", "sehiradi", uyeler.plaka);
            return View(uyeler);
        }

        // GET: uyelers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            uyeler uyeler = await db.uyeler.FindAsync(id);
            if (uyeler == null)
            {
                return HttpNotFound();
            }
            ViewBag.meslekid = new SelectList(db.meslek, "meslekid", "meslekad", uyeler.meslekid);
            ViewBag.plaka = new SelectList(db.sehirler, "plaka", "sehiradi", uyeler.plaka);
            return View(uyeler);
        }

        // POST: uyelers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "uyeid,kuladi,sifre,adsoyad,dogtar,cinsiyet,adres,plaka,email,meslekid,onay")] uyeler uyeler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uyeler).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.meslekid = new SelectList(db.meslek, "meslekid", "meslekad", uyeler.meslekid);
            ViewBag.plaka = new SelectList(db.sehirler, "plaka", "sehiradi", uyeler.plaka);
            return View(uyeler);
        }

        // GET: uyelers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            uyeler uyeler = await db.uyeler.FindAsync(id);
            if (uyeler == null)
            {
                return HttpNotFound();
            }
            return View(uyeler);
        }

        // POST: uyelers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            uyeler uyeler = await db.uyeler.FindAsync(id);
            db.uyeler.Remove(uyeler);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E_ticaret_MVC_projesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My E-Ticaret Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript">
        var GB_ROOT_DIR = "../../greybox/";
    </script>
    <script type="text/javascript" src="~/greybox/AJS.js"></script>
    <script type="text/javascript" src="~/greybox/AJS_fx.js"></script>
    <script type="text/javascript" src="~/greybox/gb_scripts.js"></script>
    <link href="~/greybox/gb_styles.css" rel="stylesheet" type="text/css" />


</head>
<body>
    <table class="tablo">
        <tr>
            <td colspan="3" class="ustmenu">
                @*menü başladı *@
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="#">KAPATIYORUZ.COM</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="#">ANA SAYFA</a>
                                </li>
                                @if (Session["uyem"] == null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("create","uyelers")">üYE OL</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">üYE Bilgileri GÜncelle</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("guv_cikis")">Güvenli Çıkış</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link" href="#">İLETİŞİM</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        KATEGORİLER
                                    </a>
                                    <ul class="dropdown-menu">

                                        @{ Html.RenderAction("kategori_doldur", "home");}
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

                @*menü bitti*@




            </td>
        </tr>
        <tr>
            <td colspan="2" class="icerik_td"><div class="icerik">@RenderBody()</div></td>
            <td width="25%">
                <div class="div1">
                    @ViewBag.giris_sonuc
                    @{ Html.RenderPartial("~/Views/Home/login_giris.cshtml");}

                </div>
            </td>
            </td>
        </tr>
        <tr>
            <td colspan="3" class="altbilgi_td"><div class="div2">Alt bilgi</div></td>
        </tr>
    </table>




    @Scripts.Render("~/bundles/jquery")

    <script src="~/Scripts/bootstrap.bundle.js"></script>

</body>
</html>

E_ticaret_MVC_projesi/Views/Shared/_benim_sablon.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <b>Bu sitemizin şablon kısmı</b>
        <a href="">Link 1</a>  <a href="">Link 2</a>

        @RenderBody()
    </div>
</body>
</html>