E_ticaret_MVC_projesi/Models/Sepet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E_ticaret_MVC_projesi.Models
{

    public class Sepet
    {  
        private List<Sepetlik> _sepetim = new List<Sepetlik>();
        public List<Sepetlik> Sepetim { get => _sepetim; }
        public void Sepete_ekle(urunler gelen_urun,byte adet)
        {
            var varolan_urun = _sepetim.FirstOrDefault(x => x.urun.urunid == gelen_urun.urunid);
            if (varolan_urun == null)//sepette bu ürün yok yani ilk kez eklenecek
            {
                _sepetim.Add(new Sepetlik { urun = gelen_urun, adet = 1 });
            }
            else if (adet == 0) varolan_urun.adet += 1;//tekrar linkle ürün seçilir ve  gelinirse 
            else varolan_urun.adet = adet;//adet kutusunda artım azalalım yapıp sepet sayfası formundan gelinirse
        }
        public void Sepeten_sil(urunler silinecek_urun)
        {
            _sepetim.RemoveAll(x=>x.urun.urunid==silinecek_urun.urunid);
        }

        public double Sepet_toplami()
        {
            return _sepetim.Sum(x => x.urun.fiyat * x.adet);
        }
        public void Sepeti_temizle()
        {
            _sepetim.Clear();
        }
    }
}

E_ticaret_MVC_projesi/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using E_ticaret_MVC_projesi.Models;
namespace E_ticaret_MVC_projesi.Controllers
{
    public class SepetController : Controller
    {
        E_ticaretEntities db = new E_ticaretEntities();

        public Sepet sepeti_getir()
        {
            var sepetimiz = (Sepet)Session["sepetimiz"];
            if (sepetimiz ==null)//sepet sessionda yok ilk ürün
            {
                sepetimiz = new Sepet();
                Session["sepetimiz"] = sepetimiz;
            }
            return sepetimiz;
        }

        public ActionResult Index(int? yeni_sip_no)
        {
            if (yeni_sip_no != null)
            {
                ViewBag.msj = "Siparişiniz alındı .Siparis no=" + yeni_sip_no;
                sepeti_getir().Sepeti_temizle();
            }

            return View(sepeti_getir());
        }

        public async Task<ActionResult> sepete_ekle(int urunid,byte? adet)
        {
            var _adet = adet ?? 0;//linkle gelinirse urunler sayfasından adet 0
            var eklenecek_urun = await db.urunler.FirstOrDefaultAsync(x => x.urunid == urunid);
            if (eklenecek_urun!=null)
            {
                sepeti_getir().Sepete_ekle(eklenecek_urun, _adet);
            }
            return RedirectToAction("index");
        }

        public async Task<ActionResult> sepetten_sil(int urunid)
        {
          
            var silinecek_urun = await db.urunler.FirstOrDefaultAsync(x => x.urunid == urunid);
            if (silinecek_urun != null)
            {
                sepeti_getir().Sepeten_sil(silinecek_urun);
            }
            return RedirectToAction("index");
        }
        public async Task<ActionResult> sepeti_temizle()
        {
            sepeti_getir().Sepeti_temizle();
            return RedirectToAction("index");
        }

        }
    }

E_ticaret_MVC_projesi/Controllers/SiparislerController.cs
using E_ticaret_MVC_projesi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace E_ticaret_MVC_projesi.Controllers
{
    public class SiparislerController : Controller
    {
        // GET: Siparisler
        E_ticaretEntities db = new E_ticaretEntities();
        public async Task<ActionResult> siparis_gec()
        {
            var sepetimiz= (Sepet)Session["sepetimiz"];
            var yeni_sip_no = db.siparisler.Max(x => x.sipno);
            yeni_sip_no += 1;

            foreach (var sepetteki_urun in sepetimiz.Sepetim)
            {
                siparisler yeni_sip_kaydi = new siparisler()
                {
                    urunid = sepetteki_urun.urun.urunid,
                    adet = sepetteki_urun.adet,
                    sipno = yeni_sip_no,
                    uyeid = ((uyeler)Session["uyem"]).uyeid,
                    sip_tarihi = DateTime.Now
                };
                db.siparisler.Add(yeni_sip_kaydi);
                await db.SaveChangesAsync();
            }

            return RedirectToAction("index", "Sepet", new { yeni_sip_no });
        }
    }
}

E_ticaret_MVC_projesi/Views/Sepet/Index.cshtml
@model E_ticaret_MVC_projesi.Models.Sepet

@{
    Layout = null;
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/jquery")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <script>
        $(document).on('click', '.number-spinner button', function () {
            var btn = $(this),
                oldValue = btn.closest('.number-spinner').find('input').val().trim(),
                newVal = 0;

            if (btn.attr('data-dir') == 'up') {
                newVal = parseInt(oldValue) + 1;
            } else {
                if (oldValue > 1) {
                    newVal = parseInt(oldValue) - 1;
                } else {
                    newVal = 1;
                }
            }
            btn.closest('.number-spinner').find('input').val(newVal);
        });
    </script>
</head>
<body>
    @ViewBag.msj
    <table class="table">
        <tr>
            <th>Resim</th>
            <th>Ürün Adı</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Sepetten Çıkar</th>
        </tr>

        @foreach (var item in Model.Sepetim)
        {
            <tr>
                <td><img src="~/urun_resimleri/@item.urun.resim" height="80" width="80"></td>
                <td>@item.urun.urunadi  </td>
                <td>
                    @*@item.adet*@
                    @using (Html.BeginForm("sepete_ekle", "sepet"))
                    {
                        <div class="input-group number-spinner">
                            <span class="input-group-btn">
                                <button name="urunid" class="btn btn-default" value="@item.urun.urunid" data-dir="dwn" onclick="'this.form.submit()'">-</button>
                            </span>

                            <input name="adet" type="text" class="form-control text-center" value="@item.adet">

                            <span class="input-group-btn">
                                <button name="urunid" class="btn btn-default" value="@item.urun.urunid" data-dir="up" onclick="'this.form.submit()'">+</button>
                            </span>
                        </div>
                    }

                </td>
                <td>@item.urun.fiyat </td>
                <td>@(item.urun.fiyat*item.adet) </td>
                <td>
                    @Html.ActionLink("SİL", "sepetten_sil", new { urunid = item.urun.urunid }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
        <tr><td colspan="6" align="right"><b>Sepet Toplami=</b> @Model.Sepet_toplami() TL</td></tr>
        <tr>
            <td colspan="6" align="right">
                @Html.ActionLink("SATIN AL","siparis_gec","Siparisler",null,new { @class = "btn btn-success" })
                @Html.ActionLink("TEMİZLE", "sepeti_temizle", null, new { @class = "btn btn-primary" })

            </td>
        </tr>
    </table>
</body>
</html>